# Generated by Django 5.0.4 on 2024-06-16 14:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('name', django.db.models.manager.Manager()),
            ],
        ),
    ]
