# Generated by Django 5.0.4 on 2024-06-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='name',
            new_name='username',
        ),
    ]
